name: pawshub
services:


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pawshub-backend
    restart: always
    ports:
      - "5001:5001"
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
